# Generated by Django 5.2.5 on 2025-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Restaurant Site', max_length=100)),
                ('site_tagline', models.CharField(default='Delicious food delivered fresh to your door', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone', models.CharField(default='(555) 123-4567', max_length=20)),
                ('email', models.EmailField(default='info@restaurant.com', max_length=254)),
                ('address', models.TextField(default='123 Food Street, City')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code (e.g., +1234567890)', max_length=20, null=True)),
                ('meta_description', models.TextField(default='Experience exceptional dining with fresh, delicious food delivered to your door.', max_length=160)),
                ('meta_keywords', models.CharField(default='restaurant, food delivery, dining, fresh food', max_length=255)),
                ('monday_hours', models.CharField(default='11:00 AM - 10:00 PM', max_length=50)),
                ('tuesday_hours', models.CharField(default='11:00 AM - 10:00 PM', max_length=50)),
                ('wednesday_hours', models.CharField(default='11:00 AM - 10:00 PM', max_length=50)),
                ('thursday_hours', models.CharField(default='11:00 AM - 10:00 PM', max_length=50)),
                ('friday_hours', models.CharField(default='11:00 AM - 11:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(default='11:00 AM - 11:00 PM', max_length=50)),
                ('sunday_hours', models.CharField(default='12:00 PM - 9:00 PM', max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2.99, max_digits=5)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('is_delivery_enabled', models.BooleanField(default=True)),
                ('is_pickup_enabled', models.BooleanField(default=True)),
                ('footer_text', models.TextField(default='© 2024 Restaurant Site. All rights reserved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
